GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Orava Koira",
  "number": "040-987654321"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "040-987654321"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Koira"
}
###
DELETE http://localhost:3001/api/persons/3
